name: Docker Image CI

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: ["main"]

env:
  ECS_CLUSTER: ligo-cluster-1
  ECS_SERVICE: ligo-rag-service
  CONTAINER_NAME: rag-server
  TASK_DEFINITION_FAMILY: ligo-rag-task
  AWS_REGISTRY_URL: null
  REPOSITORY_NAME: ligo/poly-vault

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo "COHERE_API_KEY=${{ secrets.COHERE_API_KEY }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract metadata (tags, labels) for Docker image
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ steps.ecr.outputs.registry }}/ligo/poly-vault
          tags: type=sha,prefix=

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          context: . # Defines the build's context as the set of files located in the specified path
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.TASK_DEFINITION_FAMILY }} \
            --query 'taskDefinition' > task-definition.json

        # Removes metadata so it can be reused for the new deployment.
      - name: Clean task definition
        run: |
          jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .deregisteredAt, .registeredBy, .enableFaultInjection)' task-definition.json > cleaned-task-definition.json
          mv cleaned-task-definition.json task-definition.json

        # This plugs the new image into the existing task definition, ready for ECS.
      - name: Render updated task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.meta.outputs.tags }}
          environment-variables: |
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION=${{ secrets.AWS_REGION }}

      - name: Deploy to ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
